title: "Oasis Flooring"
description: "We specialize in providing services to install, maintain, and repair floors for residential and commercial customers."
images: 
  - "oasis-images/489321020_17847512292447196_5642844424090782432_n.jpg"

logo: "logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  # dribbble: "#"
  instagram: "https://www.instagram.com/oasisflooringllc/"
  facebook: "https://www.facebook.com/profile.php?id=61574796216837"
  # twitter: "#"

location:
  - "Sahuarita, Arizona"

contact:
  - "Oasis Flooring LLC"
  - "oasisflooringaz@gmail.com"
  - "(843) 642-6752"

copyright: "© 2025 Oasis Flooring All Rights Reserved"

